// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };

// export default {
//   "login": "AshishKumar409",
//   "id": 76529660,
//   "node_id": "MDQ6VXNlcjc2NTI5NjYw",
//   "avatar_url": "https://avatars.githubusercontent.com/u/76529660?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/AshishKumar409",
//   "html_url": "https://github.com/AshishKumar409",
//   "followers_url": "https://api.github.com/users/AshishKumar409/followers",
//   "following_url": "https://api.github.com/users/AshishKumar409/following{/other_user}",
//   "gists_url": "https://api.github.com/users/AshishKumar409/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/AshishKumar409/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/AshishKumar409/subscriptions",
//   "organizations_url": "https://api.github.com/users/AshishKumar409/orgs",
//   "repos_url": "https://api.github.com/users/AshishKumar409/repos",
//   "events_url": "https://api.github.com/users/AshishKumar409/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/AshishKumar409/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": "Ashish Kumar Nath",
//   "company": null,
//   "blog": "",
//   "location": null,
//   "email": null,
//   "hireable": null,
//   "bio": "Aspiring Full Stack Developer.",
//   "twitter_username": null,
//   "public_repos": 29,
//   "public_gists": 0,
//   "followers": 2,
//   "following": 9,
//   "created_at": "2020-12-23T16:15:20Z",
//   "updated_at": "2022-02-27T05:49:27Z"
// }


export default {
  "login": "prof3ssorSt3v3",
  "id": 1200328,
  "node_id": "MDQ6VXNlcjEyMDAzMjg=",
  "avatar_url": "https://avatars.githubusercontent.com/u/1200328?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/prof3ssorSt3v3",
  "html_url": "https://github.com/prof3ssorSt3v3",
  "followers_url": "https://api.github.com/users/prof3ssorSt3v3/followers",
  "following_url": "https://api.github.com/users/prof3ssorSt3v3/following{/other_user}",
  "gists_url": "https://api.github.com/users/prof3ssorSt3v3/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/prof3ssorSt3v3/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/prof3ssorSt3v3/subscriptions",
  "organizations_url": "https://api.github.com/users/prof3ssorSt3v3/orgs",
  "repos_url": "https://api.github.com/users/prof3ssorSt3v3/repos",
  "events_url": "https://api.github.com/users/prof3ssorSt3v3/events{/privacy}",
  "received_events_url": "https://api.github.com/users/prof3ssorSt3v3/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Steve Griffith",
  "company": "Algonquin College",
  "blog": "http://www.algonquincollege.com/mediaanddesign/program/mobile-application-design-and-development/",
  "location": "Ottawa, Ontario, Canada",
  "email": null,
  "hireable": null,
  "bio": "Coordinator of the Mobile Application Design & Development Program at Algonquin College",
  "twitter_username": "prof3ssorSt3v3",
  "public_repos": 152,
  "public_gists": 824,
  "followers": 839,
  "following": 1,
  "created_at": "2011-11-16T19:48:02Z",
  "updated_at": "2022-04-06T11:27:07Z"
}


